[project]
name = "rapt"
version = "0.1.0"
description = "Relational algebra parsing tools"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyparsing>=3.2.3",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.10",
]
